language: php

php:
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm

matrix:
  allow_failures:
    - php: '5.5'
    - php: '5.6'
    - php: '7.0'
    - php: hhvm

before_script:
  - composer install --dev --no-interaction
  - composer require satooshi/php-coveralls '~1.0'

script:
  - vendor/bin/phpunit
