language: php

php:
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm

before_script:
  - composer install --dev --no-interaction
  - composer require satooshi/php-coveralls '~1.0'

script:
  - vendor/bin/phpunit
